### PR TITLE
OEUI-232: Make a Draft order component reusable in all order page

### PR DESCRIPTION
**Pull request by topseySuave**
## JIRA TICKET
[OEUI-232: Make a Draft order component reusable in all order page](https://issues.openmrs.org/browse/OEUI-232)

## SUMMARY
This should make a Draft order component reusable and visible in all order page.

### CODE REVIEW

**Comment by mogoodrich** [comment]
Looks like there's a failing test? Possibly caused by merging in another branch?

**Comment by topseySuave** [comment]
@mogoodrich we are currently working on it... : )

**Comment by jomadoye** [comment]
@topseySuave Is this ready for review?

**Comment by topseySuave** [comment]
@jomadoye @IAMOTZ this is ready to be reviewed...

**Comment by mogoodrich** [comment]
How are we looking for this? Are we ready to merge this in?  It's be open for a while. @topseySuave  @Efosaok @rhenshaw56  @IAMOTZ  @jomadoye

**Comment by topseySuave** [comment]
Yes, @mogoodrich This PR tampers with the action buttons, But because they are already working in the master branch, We decided to leave this for now and work on other tickets that actually fixes the action buttons and stuff, of this PR so when everything is in place we can merge it all together.

**Pull request closed without merging**
