### PR TITLE
OEUI-251:Remove the order history in lab order entry page

### PR DESCRIPTION
**Pull request by Rhotimee**
### **JIRA TICKET NAME**
[OEUI-251 Remove the order history in lab order entry page](https://issues.openmrs.org/browse/OEUI-251)

### **Summary**
- The aim of this PR is to remove the lab order history from the lab order entry page without breaking any existing functionality in the application.

## I have checked that on this Pull request

- [x] I can sucessfully create Drug orders
- [x] I can sucessfully create Lab orders
- [x] I can sucessfully search for drug orders

### CODE REVIEW

**Comment by IAMOTZ** [comment]
Hi @Rhotimee 
Please remove all instance of `fetchLabOrders` in `LabEntryForm.jsx` since the lab orders are not more displayed in the `LabEntryForm`.

**Comment by IAMOTZ** [comment]
After successfully adding a lab order, you should redirect the user to the orders list page so that he/she can see the order that he/she has just added.
The redirection can be done in this block of code:
```
componentDidUpdate(prevProps, prevState) {
    ...
    if (added && labOrderData !== prevProps.createLabOrderReducer.labOrderData) {
      successToast('lab order successfully created');
      this.props.dispatch(fetchLabOrders(null, this.props.patient.uuid));
    }
    if (error) {
      errorToast(errorMessage);
    }
    ...
  }
```

**Comment by Rhotimee** [comment]
I have attended to the feedback and made changes where necessary @IAMOTZ. Kindly review and approve. Thank you.

**Comment by Rhotimee** [comment]
Note: The Coveralls test coverage is reduced because of the test files I removed.

**Comment by topseySuave** [comment]
Please fix the failing coverage

**Pull request merged**
