### PR TITLE
OEUI-29:Initial project setup with the bug fixes

### PR DESCRIPTION
**Pull request by geofrocker**
## JIRA TICKET NAME:
[OEUI-29:Setup base application](https://issues.openmrs.org/browse/OEUI-29)
### SUMMARY:
Fix the bugs in the base application of the project on which the team will develop the project

### CODE REVIEW

**Comment by geofrocker** [comment]
@dkayiwa

**Comment by dkayiwa** [comment]
Can you squash the commits into one?

**Comment by geofrocker** [comment]
@dkayiwa The second commit message only comes after resolving merge conflicts otherwise all the previous commits have been squashed into one(OEUI-29:Initial project setup)

**Comment by dkayiwa** [comment]
Have you seen the merge conflicts?

**Comment by geofrocker** [comment]
@dkayiwa I seen the merge conflicts and have resolved them

**Comment by dkayiwa** [comment]
now can you squash the commits into one?

**Comment by geofrocker** [comment]
The second commit message is auto generated after resolving the merge conflicts

**Comment by dkayiwa** [comment]
Can you take a look at the tips here on how to have only one commit showing on the pull request? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by geofrocker** [comment]
Okay

**Comment by geofrocker** [comment]
@dkayiwa The issues have been resolved

**Pull request merged**
