### PR TITLE
UHM-4934: Create "circular workflow" for adding Lab Orders from the Lab Workflow module

### PR DESCRIPTION
**Pull request by mogoodrich**
### **JIRA TICKET NAME**
[OEUI-1234](https://mocklink) mock text

### **Summary**
- sample summary

## I have checked that on this Pull request

- [ ] I can sucessfully create Drug orders
- [ ] I can sucessfully create Lab orders
- [ ] I can sucessfully search for drug orders

### CODE REVIEW

**Comment by mogoodrich** [comment]
This code could use a big refactor, but OWAs are pretty muc orphaned at this point... @mseaton  @cioan  adding you as reviewers if you care to take a look... what I added feels like a hack, but at this point...

**Review by mseaton — APPROVED** [review]
I skimmed it.  Nothing stands out.  LGTM

**Review by cioan — APPROVED** [review]
LGTM! Thanks @mogoodrich !

**Comment by mogoodrich** [comment]
Thanks @cioan  and @mseaton...

**Pull request merged**
