### PR TITLE
OEUI-243: Tweak Orders List To Reflect Mockup properly

### PR DESCRIPTION
**Pull request by Efosaok**
#### JIRA TICKET NAME
[OEUI-143](https://issues.openmrs.org/browse/OEUI-243)

#### Summary
- Remove borders from Orders list accordion title

### CODE REVIEW

**Comment by Efosaok** [comment]
@jomadoye 
I saw no need to implement a breadcrumb as the order-entry page is just a single page and each rendered component has a header that indicates what the current component is.
I would be editing the ticket description to correspond with my existing implementation.

**Comment by jomadoye** [comment]
@Efosaok I see your point, but I would like to point out that most if not all OWA's have a breadcrumb that tells it's user what part of the app it's on, 
you can find samples 
(https://github.com/openmrs/openmrs-owa-addonmanager/blob/master/app/js/components/breadCrumb/BreadCrumbComponent.jsx) or (https://github.com/openmrs/openmrs-owa-cohortbuilder/blob/master/app/js/components/breadCrumb/breadCrumbComponent.jsx).

In order entry case, we can notify the user when they are on the `homePage` or `DrugOrderPage` or `LabOrderPage`.
You can also see a UI sample of the breadcrumb in Dave's mockup.

An addon would be to make the `breadcrumb component` reusable by moving it to `react-components`, but let's take it step by step.

**Comment by mogoodrich** [comment]
I agree that it would be good to have basic breadcrumbs to be consistent with the other apps, if for no other reason.

I'm fine with handling that as part of this ticket, or creating a new ticket and merging this changes as-is.

**Comment by Efosaok** [comment]
Never Mind, I'll implement it on this ticket.

Thanks.

**Comment by IAMOTZ** [comment]
`...To Reflect Mockup properly...`
I noticed that the mockup added stripes to the list to make it easier to read like this: 
screen shot 2018-08-24 at 12 30 25 pm
But that is not reflected in the actual implementation as shown here: 
screen shot 2018-08-24 at 12 31 24 pm

**Comment by IAMOTZ** [comment]
_`...To Reflect Mockup properly...`_
There is more spacing around the each order row on the mockup and this makes it easier to read:
screen shot 2018-08-24 at 12 40 47 pm
Compared to this in the actual implementation:
screen shot 2018-08-24 at 12 41 46 pm

**Comment by IAMOTZ** [comment]
_`...To Reflect Mockup Properly...`_
The Order details on the Mockup is aligned to the left:
screen shot 2018-08-24 at 12 40 47 pm
But the alignment is to the center in the actual implementation: 
screen shot 2018-08-24 at 12 41 46 pm

**Comment by dkayiwa** [comment]
@Efosaok do you know why this was opened 23 days ago but still not yet merged?

**Comment by dkayiwa** [comment]
Closing this until i get a response to the above.

**Pull request closed without merging**
