### PR TITLE
OEUI-282: (New) and (Revise) should not appear on order list

### PR DESCRIPTION
**Pull request by Daramola98**
### **JIRA TICKET NAME**
[OEUI-282: (New) and (Revise) should not appear on order list](https://issues.openmrs.org/browse/OEUI-282)

### **Summary**
- Remove (New) and (Revise) from the order list
- New and Revise should show on draft list

## I have checked that on this Pull request

- [x] I can sucessfully create Drug orders
- [x] I can sucessfully create Lab orders
- [x] I can sucessfully search for drug orders

### CODE REVIEW

**Comment by dkayiwa** [comment]
Any tests to accompany this change?

**Comment by Daramola98** [comment]
> Any tests to accompany this change?

No tests has it is data coming from the API

**Comment by dkayiwa** [comment]
I do not understand your response.

**Comment by Daramola98** [comment]
No functionality changed just manipulating data that is displayed, would be like testing if the string methods used does what they are supposed to do

**Comment by dkayiwa** [comment]
Do you mean we cannot have tests to ensure that "(New) and (Revise) should not appear on order list"?

**Comment by Daramola98** [comment]
So the data that comes from the API contains (NEW) or (REVISE), that data is passed to the component and it's been manipulated in the component to remove them, we can have test that ensure this but snapshots were used for testing components but I can write a test case that would handle that, but it would never fail because it would be mock data that would be passed to the props, so its just like testing if the string I am passing to props which contain (NEW) or (REVISE) responds to the substring method.

**Comment by Daramola98** [comment]
what do you think? should I go ahead an write a test that does this?

**Comment by Daramola98** [comment]
Ok will do this, Thanks

**Comment by dkayiwa** [comment]
But does it make sense to you?

**Comment by Daramola98** [comment]
Yes it does, will have to make sure the value of that column does not have NEW or REVISE

**Comment by mseaton** [comment]
@Daramola98 and @dkayiwa just noticing this conversation and a bit concerned that we are parsing a display property of a REST response in order to get the information we need here.  Can't we get the actual orderable and it's display property properly, rather than resorting to a somewhat hacky need to substring?

**Comment by Daramola98** [comment]
I just checked the rest response again and there seems to be a drug display object that contains just the drug name, I think I would refactor to use just that instead of the substring method @dkayiwa @mseaton

**Comment by mseaton** [comment]
@Daramola98 perfect.

**Comment by Daramola98** [comment]
@mseaton @dkayiwa I have made the necessary changes, Please review Thanks

**Pull request merged**
